# Generated by Django 4.1.5 on 2023-01-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_address_only_one_default_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
    ]
