# Generated by Django 4.1.5 on 2023-01-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_remove_address_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(),
        ),
    ]
