# Generated by Django 4.1.4 on 2022-12-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
