# Generated by Django 4.1.4 on 2022-12-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_address_alter_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
