# Generated by Django 4.1.4 on 2022-12-26 16:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_address_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2022, 12, 26, 16, 47, 36, 806728, tzinfo=datetime.timezone.utc))),
                ('verify_failed_count', models.PositiveIntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
