# Generated by Django 4.1.4 on 2022-12-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_forgotpasswordcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForgotPasswordCode',
        ),
    ]
