# Generated by Django 4.1.7 on 2023-02-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_variants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='num_sold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
