# Generated by Django 4.1.7 on 2023-02-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_variants', '0002_productvariant_num_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='num_sold',
            field=models.IntegerField(default=0),
        ),
    ]
