# Generated by Django 4.1.7 on 2023-02-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_variants', '0003_alter_productvariant_num_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='num_sold',
        ),
    ]
