# Generated by Django 4.1.7 on 2023-02-26 11:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_link', models.URLField(null=True)),
                ('check_payment_link', models.URLField(null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_at', models.DateTimeField(default=None, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
