# Generated by Django 4.1.6 on 2023-02-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="payment_link",
            new_name="check_order_link",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="amount",
            new_name="paid_amount",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
        migrations.AddField(
            model_name="transaction",
            name="order_link",
            field=models.URLField(default=None, null=True),
        ),
    ]
