# Generated by Django 4.1.6 on 2023-02-07 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0002_rename_payment_link_transaction_check_order_link_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="check_order_link",
            new_name="check_payment_link",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="order_link",
            new_name="payment_link",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=None,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
