# Generated by Django 4.1.6 on 2023-02-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        (
            "transactions",
            "0003_rename_check_order_link_transaction_check_payment_link_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="check_payment_link",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_link",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
