# Generated by Django 4.1.6 on 2023-02-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_transaction_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="owner",
        ),
    ]
