# Generated by Django 4.1.7 on 2023-02-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_remove_transaction_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='check_payment_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_link',
            field=models.URLField(null=True),
        ),
    ]
