# Generated by Django 4.1.5 on 2023-01-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('recover_token', models.CharField(default=None, max_length=16, null=True)),
                ('expired_at', models.DateTimeField()),
            ],
        ),
    ]
