# Generated by Django 4.1.4 on 2022-12-26 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgotpasswordcode',
            old_name='email',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='forgotpasswordcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 17, 31, 21, 891039, tzinfo=datetime.timezone.utc)),
        ),
    ]
