# Generated by Django 4.1.5 on 2023-01-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordcode',
            name='expired_at',
            field=models.DateTimeField(),
        ),
    ]
