# Generated by Django 4.1.4 on 2023-01-08 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 10, 0, 45, 547429, tzinfo=datetime.timezone.utc)),
        ),
    ]
