# Generated by Django 4.1.5 on 2023-01-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpasswordcode',
            name='recover_token',
        ),
    ]
