# Generated by Django 4.1.4 on 2022-12-26 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_rename_email_forgotpasswordcode_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 17, 58, 52, 534035, tzinfo=datetime.timezone.utc)),
        ),
    ]
