# Generated by Django 4.1.4 on 2023-01-08 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_alter_forgotpasswordcode_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 19, 31, 10, 141384, tzinfo=datetime.timezone.utc)),
        ),
    ]
