# Generated by Django 4.1.4 on 2023-01-10 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_alter_forgotpasswordcode_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 7, 33, 53, 233198, tzinfo=datetime.timezone.utc)),
        ),
    ]
