# Generated by Django 4.1.5 on 2023-01-13 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_alter_forgotpasswordcode_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 16, 30, 55, 282127, tzinfo=datetime.timezone.utc)),
        ),
    ]
