# Generated by Django 4.1.5 on 2023-01-21 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0016_alter_forgotpasswordcode_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 12, 4, 57, 848364, tzinfo=datetime.timezone.utc)),
        ),
    ]
