# Generated by Django 4.1.5 on 2023-01-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0021_alter_forgotpasswordcode_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordcode',
            name='expired_at',
            field=models.DateTimeField(),
        ),
    ]
