# Generated by Django 4.1.6 on 2023-02-08 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_reviewed_products_alter_order_discount_ticket"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
            preserve_default=False,
        ),
    ]
