# Generated by Django 4.1.4 on 2022-12-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_user_review_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='owner',
        ),
    ]
