# Generated by Django 4.1.6 on 2023-02-08 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_feature_vector"),
        ("reviews", "0004_remove_review_product_review_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
            preserve_default=False,
        ),
    ]
