# Generated by Django 4.1.4 on 2022-12-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RAW_VALUE', 'Raw value'), ('PERCENT', 'Percent')], default='RAW_VALUE', max_length=16)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
