# Generated by Django 4.1.4 on 2022-12-26 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discount_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountticket',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
