# Generated by Django 4.1.6 on 2023-02-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount_tickets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="discountticket",
            name="correct_datetime",
        ),
        migrations.AddConstraint(
            model_name="discountticket",
            constraint=models.CheckConstraint(
                check=models.Q(("start_at__lte", models.F("end_at"))),
                name="correct_datetime",
            ),
        ),
    ]
