# Generated by Django 4.1.5 on 2023-01-27 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountticket',
            name='saved_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
