# Generated by Django 4.1.5 on 2023-01-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount_tickets', '0002_discountticket_saved_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountticket',
            old_name='end_date',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='discountticket',
            old_name='start_date',
            new_name='start_at',
        ),
    ]
