# Generated by Django 4.1.7 on 2023-02-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_tickets', '0002_remove_discountticket_correct_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountticket',
            name='send_notification',
            field=models.BooleanField(default=False),
        ),
    ]
