# Generated by Django 4.1.5 on 2023-01-27 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount_tickets', '0003_rename_end_date_discountticket_end_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketUserRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('custom_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='discount_tickets.discountticket')),
                ('discount_ticket', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='discountticket',
            name='saved_users',
        ),
        migrations.AddField(
            model_name='discountticket',
            name='saved_users',
            field=models.ManyToManyField(
                blank=True, through='discount_tickets.TicketUserRel', to=settings.AUTH_USER_MODEL),
        ),

    ]
