# Generated by Django 4.1.5 on 2023-01-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount_tickets', '0004_ticketuserrel_alter_discountticket_saved_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketuserrel',
            old_name='custom_user',
            new_name='user',
        ),
    ]
