# Generated by Django 4.1.5 on 2023-01-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_tickets', '0006_alter_ticketuserrel_discount_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountticket',
            name='type',
        ),
        migrations.RemoveField(
            model_name='discountticket',
            name='value',
        ),
        migrations.AddField(
            model_name='discountticket',
            name='percent',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discountticket',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
