# Generated by Django 4.1.5 on 2023-01-27 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_tickets', '0007_remove_discountticket_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountticket',
            name='percent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(99)]),
        ),
    ]
