# Generated by Django 4.1.5 on 2023-01-21 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_remove_cartitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='owner',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
