# Generated by Django 4.1.5 on 2023-01-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_cartit_order_i_3a3082_idx',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
    ]
