# Generated by Django 4.1.5 on 2023-01-22 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_owner'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='cart_cartit_order_i_3a3082_idx',
            old_name='cart__order_i_cd8be6_idx',
        ),
    ]
