# Generated by Django 4.1.5 on 2023-01-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_cart_cartit_order_i_3a3082_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
