# Generated by Django 4.1.7 on 2023-02-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='amount',
        ),
    ]
