# Generated by Django 4.1.5 on 2023-01-25 19:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_types', '0002_rename_quantity_producttype_stocks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0004_remove_cartitem_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product_type', 'owner')},
        ),
    ]
