# Generated by Django 4.1.5 on 2023-01-24 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=orders.models.generate_code, max_length=8, unique=True)),
                ('stage', models.CharField(choices=[('TO_PAY', 'To pay'), ('TO_SHIP', 'To ship'), ('TO_RECEIVE', 'To receive'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='TO_PAY', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
