# Generated by Django 4.1.4 on 2023-01-02 05:44

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=orders.models.generate_code, max_length=8, unique=True)),
                ('stage', models.CharField(choices=[('TO_PAY', 'To pay'), ('TO_SHIP', 'To ship'), ('TO_RECEIVE', 'To receive'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='TO_PAY', max_length=32)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
