# Generated by Django 4.1.6 on 2023-02-08 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_feature_vector"),
        ("discount_tickets", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reviewed_products",
            field=models.ManyToManyField(null=True, to="products.product"),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="discount_tickets.discountticket",
            ),
        ),
    ]
