# Generated by Django 4.1.4 on 2022-12-25 04:12

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default=orders.models.generate_code, max_length=8, unique=True),
        ),
    ]
