# Generated by Django 4.1.6 on 2023-02-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_feature_vector"),
        ("orders", "0002_order_reviewed_products_alter_order_discount_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="reviewed_products",
            field=models.ManyToManyField(blank=True, to="products.product"),
        ),
    ]
