# Generated by Django 4.1.5 on 2023-01-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
    ]
