# Generated by Django 4.1.5 on 2023-01-28 15:20

from django.db import migrations, models
import orders.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address_alter_order_discount_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default=orders.helpers.generate_code, max_length=12),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('code',), name='unique_code'),
        ),
    ]
