# Generated by Django 4.1.6 on 2023-02-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_reviewed_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_items",
        ),
        migrations.RemoveField(
            model_name="order",
            name="reviewed_products",
        ),
    ]
