# Generated by Django 4.1.7 on 2023-02-22 21:43

from django.db import migrations, models
import orders.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default=orders.helpers.generate_code, max_length=12),
        ),
    ]
