# Generated by Django 4.1.5 on 2023-01-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='quantity',
            new_name='stocks',
        ),
    ]
