# Generated by Django 4.1.5 on 2023-01-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='size',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
