# Generated by Django 4.1.5 on 2023-01-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_types', '0002_rename_available_producttype_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttype',
            unique_together={('id', 'color', 'size')},
        ),
    ]
