# Generated by Django 4.1.4 on 2022-12-25 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_types', '0002_alter_producttype_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
