# Generated by Django 4.1.5 on 2023-01-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_types', '0002_alter_producttype_color_alter_producttype_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='color',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='size',
            field=models.CharField(max_length=16),
        ),
    ]
