# Generated by Django 4.1.5 on 2023-01-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_feature_vector'),
        ('product_types', '0003_alter_producttype_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttype',
            unique_together={('color', 'size', 'product')},
        ),
    ]
