# Generated by Django 4.1.4 on 2022-12-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
