# Generated by Django 4.1.4 on 2022-12-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_items', '0002_remove_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='owner',
        ),
    ]
