# Generated by Django 4.1.4 on 2022-12-25 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_items', '0003_rename_user_cartitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(default='Red', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.URLField(default='http://localhost:3000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='XL', max_length=16),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['order'], name='cart_items__order_i_cd8be6_idx'),
        ),
    ]
