# Generated by Django 4.1.7 on 2023-02-26 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products')),
                ('description', models.TextField()),
                ('feature_vector', models.TextField(default=None, null=True)),
                ('min_price', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True)),
                ('max_price', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True)),
                ('num_sold', models.PositiveIntegerField(default=None, null=True)),
                ('stocks', models.PositiveIntegerField(default=None, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_categories.productcategory')),
                ('favorited_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
