# Generated by Django 4.1.5 on 2023-01-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating_accumulate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating_count',
        ),
    ]
