# Generated by Django 4.1.4 on 2023-01-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature_vector',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
