# Generated by Django 4.1.6 on 2023-02-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="feature_vector",
            field=models.TextField(default=None, null=True),
        ),
    ]
