# Generated by Django 4.1.5 on 2023-01-21 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_feature_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
