# Generated by Django 4.1.5 on 2023-01-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_favorite_users_product_feature_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='uploads/images/products'),
        ),
    ]
