# Generated by Django 4.1.7 on 2023-02-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_num_sold_alter_product_max_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='num_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
