# Generated by Django 4.1.5 on 2023-01-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorite_users',
        ),
    ]
