# Generated by Django 4.1.7 on 2023-02-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_num_sold_alter_product_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='num_sold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_count',
        ),
    ]
