# Generated by Django 4.1.7 on 2023-02-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_max_price_remove_product_min_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
