# Generated by Django 4.1.7 on 2023-02-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_max_price_product_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True),
        ),
    ]
