# Generated by Django 4.1.4 on 2022-12-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
