# Generated by Django 4.1.7 on 2023-02-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_sold',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
